spring:
  #start:禁用模板，直接返回static下的视图
  thymeleaf:
    enabled: false
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  #end:禁用模板，直接返回static下的视图


  #start:设置Redis支持的Spring Session
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      #添加后，redis中的key为spring:session:myproject
      namespace: myproject
  #end:设置Redis支持的Spring Session

#start:spring security配置

#end:spring secutiry配置



  #start:数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springmvc-mybatis-book?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowMultiQueries=true
    username: root
    password: 12345
  #end:数据库连接配置





  #start:redis配置
  #redis集群版
  redis:
    timeout: 6000ms
    database: 0
    cluster:
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006
      max-redirects: 3 # 获取失败 最大重定向次数
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #end:redis配置





#start:activemq配置
  activemq:
    #activemq的url
    broker-url: tcp://127.0.0.1:61616
    #用户名
    user: admin
    #密码
    password: admin
    #是否使用线程池
    pool:
      enabled: false
    #是否信任所有包
    packages:
      trust-all: true
  #默认情况下，activemq使用的是queue模式，如果要使用topic模式，必须设置为true
  jms:
    pub-sub-domain: false
    queueName: publish.queue
    topicName: publish.topic
#end:activemq配置






  #start:JPA配置
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
  #end:JPA配置





#start：mybatis的相关配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mybysj.springboot.model
#end：mybatis的相关配置

server:
  #端口号
  port: 9090
